website/config/routes.rb
Rails.application.routes.draw do
  resources :tables
  resources :improves
  resources :bads
  resources :goods
  resources :models
  root to: "application#angular"
end

website/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

website/app/models/table.rb
class Table < ApplicationRecord
end

website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def angular
	render 'layouts/application'
  end

end

website/app/controllers/bads_controller.rb
class BadsController < ActionController::API
  before_action :set_bad, only: [:show, :update, :destroy]

  # GET /bads
  # GET /bads.json
  def index
    @bads = Bad.all
    render json: @bads
  end

  # GET /bads/1
  # GET /bads/1.json
  def show
  end

  # POST /bads
  # POST /bads.json
  def create
    @bad = Bad.new(bad_params)

    if @bad.save
      render json: :index, status: :created, location: @bad
    else
      render json: @bad.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bads/1
  # PATCH/PUT /bads/1.json
  def update
    if @bad.update(bad_params)
      render :show, status: :ok, location: @bad
    else
      render json: @bad.errors, status: :unprocessable_entity
    end
  end

  # DELETE /bads/1
  # DELETE /bads/1.json
  def destroy
    @bad.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bad
      @bad = Bad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bad_params
      params.require(:bad).permit(:id, :author, :date, :body, :team)
    end
end

website/app/controllers/goods_controller.rb
class GoodsController < ActionController::API
  before_action :set_good, only: [:show, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
    render json: @goods
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
    set_good
    render json: @good
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    if @good.save
      render json: :index, status: :created, location: @good
    else
      render json: @good.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    set_good
    if @good.update(good_params)
      render json: :index, status: :ok, location: @good
    else
      render json: @good.errors, status: :unprocessable_entity
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    set_good
    @good.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:id, :author, :date, :body, :team)
    end
end

website/app/controllers/improves_controller.rb
class ImprovesController < ActionController::API
  before_action :set_improfe, only: [:show, :update, :destroy]

  # GET /improves
  # GET /improves.json
  def index
    @improves = Improve.all
    render json: @improves
  end

  # GET /improves/1
  # GET /improves/1.json
  def show
  end

  # POST /improves
  # POST /improves.json
  def create
    @improfe = Improve.new(improfe_params)

    if @improfe.save
      render json: :index, status: :created, location: @improfe
    else
      render json: @improfe.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /improves/1
  # PATCH/PUT /improves/1.json
  def update
    if @improfe.update(improfe_params)
      render :show, status: :ok, location: @improfe
    else
      render json: @improfe.errors, status: :unprocessable_entity
    end
  end

  # DELETE /improves/1
  # DELETE /improves/1.json
  def destroy
    @improfe.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_improfe
      @improfe = Improve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def improfe_params
      params.require(:improfe).permit(:id, :author, :date, :body, :team)
    end
end

website/app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    if @model.save
      render :show, status: :created, location: @model
    else
      render json: @model.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    if @model.update(model_params)
      render :show, status: :ok, location: @model
    else
      render json: @model.errors, status: :unprocessable_entity
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:table, :author, :date, :body, :team)
    end
end

website/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
    render json: @tables
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    set_table
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    if @table.save
      render json: :show, status: :created, location: @table
    else
      render json: @table.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    set_table
    if @table.update(table_params)
      render :show, status: :ok, location: @table
    else
      render json: @table.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    set_table
    @table.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
      render json: @table
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:column_name, :author, :sprint, :body, :team)
    end
end

website/app/helpers/application_helper.rb
module ApplicationHelper
end

website/app/helpers/models_helper.rb
module ModelsHelper
end

website/app/helpers/welcome_helper.rb
module WelcomeHelper
end

website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sprint Reviewer</title>
	  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<script src="https://use.fontawesome.com/886e08d705.js"></script>

   	<!-- Fonts -->
   	<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body ng-app="reviewer" ng-controller="Ctrl">
 
    <nav id="menu" class="navbar navbar-fixed-top ">
        <div class="container-fluid" style="margin-left:2%; margin-right:2%">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" style="margin-top:20px; border-color:black;">
                    <span class="icon-bar" style="background-color:black;"></span>
                    <span class="icon-bar" style="background-color:black;"></span>
                    <span class="icon-bar" style="background-color:black;"></span>
                </button>
                <a class="navbar-brand" href="#">2017-2-5</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/app/views/layouts/home.html.erb">Home</a></li>
                    <li><a href="#">Team</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Retros<span class="caret"></span></a>
                        <ul class="dropdown-menu" style="padding:0">

                            <li><a href="#"><p>2017-2-5</p></a></li>
                            <li><a href="#"><p>2017-2-6</p></a></li>
                            <li><a href="#"><p>2017-2-7</p></a></li>
                            <li><a href="#"><p>2017-2-8</p></a></li>
                            <li><a href="#"><p>more...</p></a></li>

                        </ul>
                    </li>    
                    <li><a href="#">My Account</a></li>
               
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
      
      <div class="row">

        <div class="col-sm-4">
          <div class="panel panel-good">
            <div class="panel-heading">
              <i class="fa fa-check" aria-hidden="true"></i>&nbsp;&nbsp;
				      GOOD
              <span class="toggles">
                {{table.length}} &nbsp;&nbsp;

                <i class="fa fa-plus-square-o editButton" aria-hidden="true" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal"></i>
                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                  <div class="modal-dialog">
                  
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">What went well?</h4>
                      </div>
                      <div class="modal-body">
                        <input class="addEntry" type="text" ng-model="tableInput">
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="addTable(tableInput)">Add</button>
                      </div>
                    </div>
                    
                  </div>
                </div>

              </span>
            </div>
            <div class="panel-body" id="table" ng-repeat="t in table"> 
              {{t.body}} 
			        <br><i class="fa fa-user-circle" aria-hidden="true"></i>
              &nbsp;{{t.author}}

              <span class="toggles-entry" ng-click="deleteTable(t.id)">
                <i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;
                <i class="fa fa-times" aria-hidden="true" ng-click="deleteTable(t.id)"></i>
              </span>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="panel panel-bad">
            <div class="panel-heading">
              <i class="fa fa-times" aria-hidden="true"></i>&nbsp;&nbsp;
				      BAD
              <span class="toggles">
                {{bad.length}} &nbsp;&nbsp;

                <i class="fa fa-plus-square-o editButton" aria-hidden="true" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal2"></i>
                <!-- Modal -->
                <div class="modal fade" id="myModal2" role="dialog">
                  <div class="modal-dialog">
                  
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">What wasn't so great?</h4>
                      </div>
                      <div class="modal-body">
                        <input class="addEntry" type="text" ng-model="badInput">
                      </div>
                      <div class="modal-footer">
                      {{badInput}}
                        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="addBad(badInput)">Add</button>
                      </div>
                    </div>
                    
                  </div>
                </div>

              </span>
            </div>
            <div class="panel-body" id="bad" ng-repeat="b in bad">
              {{b.body}}
              <br><i class="fa fa-user-circle" aria-hidden="true"></i>
              &nbsp;{{b.author}}

              <span class="toggles-entry" ng-click="deleteGood(g.id)">
                <i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;
                <i class="fa fa-times" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="panel panel-improve">
            <div class="panel-heading">
              <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;
              IMPROVE
              <span class="toggles">
                {{improve.length}} &nbsp;&nbsp;
                
                <i class="fa fa-plus-square-o editButton" aria-hidden="true" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal3"></i>
                <!-- Modal -->
                <div class="modal fade" id="myModal3" role="dialog">
                  <div class="modal-dialog">
                  
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">What can we improve?</h4>
                      </div>
                      <div class="modal-body">
                        <input class="addEntry" type="text" ng-model="imInput">
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="addIm(imInput)">Add</button>
                      </div>
                    </div>
                    
                  </div>
                </div>

              </span>
            </div>
            <div class="panel-body" id="improve" ng-repeat="i in improve">
              {{i.body}}
              <br><i class="fa fa-user-circle" aria-hidden="true"></i>
              &nbsp;{{i.author}}

              <span class="toggles-entry" ng-click="deleteGood(g.id)">
                <i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;
                <i class="fa fa-times" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>

      </div>

      
    </div>
    <footer class="footer">&copy 2017</footer>
  </body>
</html>

website/app/views/models/_form.html.erb
<%= form_for(model) do |f| %>
  <% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :good %>
    <%= f.text_field :good %>
  </div>

  <div class="field">
    <%= f.label :id %>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="field">
    <%= f.label :team %>
    <%= f.text_field :team %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

website/app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form', model: @model %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

website/app/views/models/index.html.erb
<h1>Models</h1>

<table>
  <thead>
    <tr>
      <th>Good</th>
      <th>Id</th>
      <th>Author</th>
      <th>Date</th>
      <th>Body</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.good %></td>
        <td><%= model.id %></td>
        <td><%= model.author %></td>
        <td><%= model.date %></td>
        <td><%= model.body %></td>
        <td><%= model.team %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_model_path(model) %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

website/app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form', model: @model %>

<%= link_to 'Back', models_path %>

website/app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Good:</strong>
  <%= @model.good %>
</p>

<p>
  <strong>Id:</strong>
  <%= @model.id %>
</p>

<p>
  <strong>Author:</strong>
  <%= @model.author %>
</p>

<p>
  <strong>Date:</strong>
  <%= @model.date %>
</p>

<p>
  <strong>Body:</strong>
  <%= @model.body %>
</p>

<p>
  <strong>Team:</strong>
  <%= @model.team %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>